-- M3A: object storage and StorageService foundation.
-- These tables store internal object metadata only. Application responses must not
-- expose bucket, object_key, storage_uri, raw NAS paths, or provider secrets.

CREATE TABLE IF NOT EXISTS data_storage_objects (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    provider VARCHAR(32) NOT NULL,
    bucket VARCHAR(255) NULL,
    object_key VARCHAR(1024) NOT NULL,
    object_version VARCHAR(128) NULL,
    etag VARCHAR(255) NULL,
    checksum VARCHAR(128) NULL,
    content_type VARCHAR(255) NULL,
    size_bytes BIGINT NULL,
    source_provider VARCHAR(32) NULL,
    source_uri_digest VARCHAR(128) NULL,
    source_path_digest VARCHAR(128) NULL,
    storage_state VARCHAR(32) NOT NULL DEFAULT 'OBJECT_STORED',
    migration_status VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUIRED',
    last_verified_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_token BIGINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_storage_object_provider_key_token (provider, bucket, object_key(255), delete_token),
    KEY idx_storage_object_provider_state (provider, storage_state),
    KEY idx_storage_object_migration_status (migration_status),
    KEY idx_storage_object_checksum (checksum),
    KEY idx_storage_object_source_digest (source_provider, source_uri_digest)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_file_object_versions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    file_id BIGINT NOT NULL,
    storage_object_id BIGINT NOT NULL,
    version_no VARCHAR(64) NULL,
    active TINYINT NOT NULL DEFAULT 1,
    storage_state VARCHAR(32) NOT NULL DEFAULT 'OBJECT_STORED',
    migration_status VARCHAR(32) NOT NULL DEFAULT 'COMPLETED',
    checksum VARCHAR(128) NULL,
    content_type VARCHAR(255) NULL,
    size_bytes BIGINT NULL,
    last_verified_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_token BIGINT NOT NULL DEFAULT 0,
    KEY idx_file_object_active_token (file_id, active, delete_token),
    KEY idx_file_object_file_state (file_id, storage_state),
    KEY idx_file_object_storage_object (storage_object_id),
    CONSTRAINT fk_file_object_file FOREIGN KEY (file_id) REFERENCES data_file_resources (id),
    CONSTRAINT fk_file_object_storage_object FOREIGN KEY (storage_object_id) REFERENCES data_storage_objects (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_object_migration_tasks (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NULL,
    file_id BIGINT NULL,
    source_provider VARCHAR(32) NOT NULL DEFAULT 'NAS',
    target_provider VARCHAR(32) NOT NULL DEFAULT 'MINIO',
    source_uri_digest VARCHAR(128) NULL,
    source_path_digest VARCHAR(128) NULL,
    target_object_id BIGINT NULL,
    migration_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    storage_state VARCHAR(32) NOT NULL DEFAULT 'MIGRATION_PENDING',
    failure_reason VARCHAR(1024) NULL,
    requested_by BIGINT NULL,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    last_verified_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_token BIGINT NOT NULL DEFAULT 0,
    KEY idx_object_migration_project_status (project_id, migration_status),
    KEY idx_object_migration_file_status (file_id, migration_status),
    KEY idx_object_migration_target_object (target_object_id),
    CONSTRAINT fk_object_migration_project FOREIGN KEY (project_id) REFERENCES core_projects (id),
    CONSTRAINT fk_object_migration_file FOREIGN KEY (file_id) REFERENCES data_file_resources (id),
    CONSTRAINT fk_object_migration_target_object FOREIGN KEY (target_object_id) REFERENCES data_storage_objects (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_file_derivatives (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    file_id BIGINT NOT NULL,
    storage_object_id BIGINT NULL,
    derivative_type VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NULL,
    content_type VARCHAR(255) NULL,
    checksum VARCHAR(128) NULL,
    size_bytes BIGINT NULL,
    storage_state VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    generation_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
    last_verified_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_token BIGINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_file_derivative_type_token (file_id, derivative_type, delete_token),
    KEY idx_file_derivative_storage_object (storage_object_id),
    CONSTRAINT fk_file_derivative_file FOREIGN KEY (file_id) REFERENCES data_file_resources (id),
    CONSTRAINT fk_file_derivative_storage_object FOREIGN KEY (storage_object_id) REFERENCES data_storage_objects (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_preview_artifacts (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    file_id BIGINT NOT NULL,
    derivative_id BIGINT NULL,
    storage_object_id BIGINT NULL,
    artifact_type VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NULL,
    content_type VARCHAR(255) NULL,
    checksum VARCHAR(128) NULL,
    size_bytes BIGINT NULL,
    preview_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
    storage_state VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    expires_at TIMESTAMP NULL,
    last_verified_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_token BIGINT NOT NULL DEFAULT 0,
    KEY idx_preview_artifact_file_status (file_id, preview_status),
    KEY idx_preview_artifact_derivative (derivative_id),
    KEY idx_preview_artifact_storage_object (storage_object_id),
    CONSTRAINT fk_preview_artifact_file FOREIGN KEY (file_id) REFERENCES data_file_resources (id),
    CONSTRAINT fk_preview_artifact_derivative FOREIGN KEY (derivative_id) REFERENCES data_file_derivatives (id),
    CONSTRAINT fk_preview_artifact_storage_object FOREIGN KEY (storage_object_id) REFERENCES data_storage_objects (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
