CREATE TABLE IF NOT EXISTS visualization_lightweight_jobs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    integration_id BIGINT NULL,
    file_id BIGINT NOT NULL,
    asset_uuid CHAR(36) NULL,
    engine_provider VARCHAR(32) NOT NULL,
    engine_type INT NOT NULL,
    lightweight_name VARCHAR(128) NULL,
    unique_code VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    progress_percent INT NOT NULL DEFAULT 0,
    model_access_address VARCHAR(512) NULL,
    viewer_available TINYINT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(64) NULL,
    last_error_message VARCHAR(512) NULL,
    station_record_json JSON NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_token BIGINT NOT NULL DEFAULT 0,
    KEY idx_vlj_project_file (project_id, file_id, deleted),
    KEY idx_vlj_project_integration (project_id, integration_id, deleted),
    KEY idx_vlj_lightweight_name (lightweight_name),
    KEY idx_vlj_unique_code (unique_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
