-- M3X-Q: persistent background queue for controlled objectification.
-- Queue rows are operational metadata only. API responses must not expose
-- storage_uri, raw NAS paths, bucket, object_key, SQL, raw row, token, or secret.

CREATE TABLE IF NOT EXISTS data_objectification_jobs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_code VARCHAR(64) NOT NULL,
    job_name VARCHAR(255) NOT NULL,
    scope_type VARCHAR(32) NOT NULL DEFAULT 'ALL_REAL_PROJECTS',
    project_ids_json TEXT NULL,
    job_status VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    target_provider VARCHAR(32) NOT NULL DEFAULT 'MINIO',
    total_files BIGINT NOT NULL DEFAULT 0,
    processed_files BIGINT NOT NULL DEFAULT 0,
    success_files BIGINT NOT NULL DEFAULT 0,
    failed_files BIGINT NOT NULL DEFAULT 0,
    skipped_files BIGINT NOT NULL DEFAULT 0,
    total_bytes BIGINT NOT NULL DEFAULT 0,
    processed_bytes BIGINT NOT NULL DEFAULT 0,
    max_files_per_tick INT NOT NULL DEFAULT 5,
    max_bytes_per_tick BIGINT NOT NULL DEFAULT 52428800,
    max_file_size_bytes BIGINT NOT NULL DEFAULT 524288000,
    continue_on_failure TINYINT NOT NULL DEFAULT 1,
    worker_lease_until TIMESTAMP NULL,
    started_at TIMESTAMP NULL,
    paused_at TIMESTAMP NULL,
    finished_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_token BIGINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_objectification_job_code_token (job_code, delete_token),
    KEY idx_objectification_job_status_lease (job_status, worker_lease_until),
    KEY idx_objectification_job_created_by (created_by),
    KEY idx_objectification_job_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_objectification_job_items (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    item_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    failure_reason VARCHAR(1024) NULL,
    retry_count INT NOT NULL DEFAULT 0,
    size_bytes BIGINT NULL,
    checksum VARCHAR(128) NULL,
    migration_task_id BIGINT NULL,
    storage_object_id BIGINT NULL,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_token BIGINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_objectification_job_file_token (job_id, file_id, delete_token),
    KEY idx_objectification_item_job_status (job_id, item_status),
    KEY idx_objectification_item_project_status (project_id, item_status),
    KEY idx_objectification_item_file (file_id),
    KEY idx_objectification_item_migration_task (migration_task_id),
    CONSTRAINT fk_objectification_item_job FOREIGN KEY (job_id) REFERENCES data_objectification_jobs (id),
    CONSTRAINT fk_objectification_item_project FOREIGN KEY (project_id) REFERENCES core_projects (id),
    CONSTRAINT fk_objectification_item_file FOREIGN KEY (file_id) REFERENCES data_file_resources (id),
    CONSTRAINT fk_objectification_item_migration_task FOREIGN KEY (migration_task_id) REFERENCES data_object_migration_task_batches (id),
    CONSTRAINT fk_objectification_item_storage_object FOREIGN KEY (storage_object_id) REFERENCES data_storage_objects (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
